---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '17.0.7'
      graalvm_is_default_installation: false
      graalvm_fact_group_name: 'graalvm_java_17'

    - role: ansible-role-graalvm

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm_java_17.general.java_version is defined
          - ansible_local.graalvm_java_17.general.java_version is version('17.0.7', '==')
          - ansible_local.graalvm_java_17.general.home is defined
          - ansible_local.graalvm_java_17.general.home is match ('/opt/graalvm/jdk-17.0.7')

    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.java_version is version('21.0.2', '==')
          - ansible_local.graalvm.general.home is defined
          - ansible_local.graalvm.general.home is match ('/opt/graalvm/jdk-21.0.2')

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
