---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ graalvm_local_archive_dir }}'
      delegate_to: localhost

    - name: download GraalVM for offline install
      get_url:
        url: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.0/graalvm-ce-java17-linux-amd64-22.3.0.tar.gz"
        dest: '{{ graalvm_local_archive_dir }}/graalvm-22.3.0-java17.tar.gz'
        force: no
        timeout: '{{ graalvm_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '17'
      graalvm_version: '22.3.0'
      graalvm_use_local_archive: true
      graalvm_redis_filename: 'graalvm-22.3.0-java17.tar.gz'
      graalvm_redis_sha256sum: '3473d8b3b1bc682e95adfb3ac1d9a59b51b0f43e2b752f2a5b550e4ebfa2fd17'

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.version is defined
          - ansible_local.graalvm.general.version is version('22.3.0', '==')
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.java_version is version('17', '==')
          - ansible_local.graalvm.general.home is defined
          - ansible_local.graalvm.general.home is match ('/opt/graalvm/graalvm-22.3.0-java17')

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
