---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ graalvm_local_archive_dir }}'
      delegate_to: localhost

    - name: download GraalVM for offline install
      get_url:
        url: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.3.0/graalvm-ce-java17-linux-amd64-21.3.0.tar.gz"
        dest: '{{ graalvm_local_archive_dir }}/graalvm-21.3.0-java17.tar.gz'
        force: no
        timeout: '{{ graalvm_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '17'
      graalvm_version: '21.3.0'
      graalvm_use_local_archive: true
      graalvm_redis_filename: 'graalvm-21.3.0-java17.tar.gz'
      graalvm_redis_sha256sum: '11d8039e0a7a31b799a6f20a0e806e4128730e9a2595a7ffdec1443539d4c3f6'

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.version is defined
          - ansible_local.graalvm.general.version is version('21.3.0', '==')
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.java_version is version('17', '==')
          - ansible_local.graalvm.general.home is defined
          - ansible_local.graalvm.general.home is match ('/opt/graalvm/graalvm-21.3.0-java17')

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
