---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ graalvm_local_archive_dir }}'
      delegate_to: localhost

    - name: download GraalVM for offline install
      get_url:
        url: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java17-linux-amd64-22.1.0.tar.gz"
        dest: '{{ graalvm_local_archive_dir }}/graalvm-22.1.0-java17.tar.gz'
        force: no
        timeout: '{{ graalvm_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '17'
      graalvm_version: '22.1.0'
      graalvm_use_local_archive: true
      graalvm_redis_filename: 'graalvm-22.1.0-java17.tar.gz'
      graalvm_redis_sha256sum: 'f11d46098efbf78465a875c502028767e3de410a31e45d92a9c5cf5046f42aa2'

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.version is defined
          - ansible_local.graalvm.general.version is version('22.1.0', '==')
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.java_version is version('17', '==')
          - ansible_local.graalvm.general.home is defined
          - ansible_local.graalvm.general.home is match ('/opt/graalvm/graalvm-22.1.0-java17')

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
