---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ graalvm_local_archive_dir }}'
      delegate_to: localhost

    - name: download GraalVM for offline install
      get_url:
        url: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.0/graalvm-ce-java11-linux-amd64-21.0.0.tar.gz"
        dest: '{{ graalvm_local_archive_dir }}/graalvm-21.0.0-java11.tar.gz'
        force: no
        timeout: '{{ graalvm_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost

  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '11'
      graalvm_version: '21.0.0'
      graalvm_use_local_archive: true
      graalvm_redis_filename: 'graalvm-21.0.0-java11.tar.gz'
      graalvm_redis_sha256sum: '4cdb5b9d0142cdaf5565fd20c5cde176d9b7c9dfd278267cab318f64f2923dbc'

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.version is defined
          - ansible_local.graalvm.general.version is version('21.0.0', '==')
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.java_version is version('11', '==')
          - ansible_local.graalvm.general.home is defined
          - ansible_local.graalvm.general.home is match ('/opt/graalvm/graalvm-21.0.0-java11')

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
