---
- name: install profile scripts (zypper)
  become: yes
  package:
    name: aaa_base
    state: present
  when: ansible_pkg_mgr == 'zypper'

# Set GRAALVM_HOME
- name: make sure /etc/profile.d exists
  become: yes
  file:
    path: /etc/profile.d
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
  when: graalvm_is_default_installation

- name: export GRAALVM_HOME and add to PATH
  become: yes
  template:
    src: graalvm.sh.j2
    dest: /etc/profile.d/graalvm.sh
    owner: root
    group: root
    mode: 'u=rw,go=r'
  when: graalvm_is_default_installation
