---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-graalvm-debian-min
    image: debian:9
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-min-online/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: debian-min-graalvm-min-online

verifier:
  name: testinfra
  directory: ../graalvm-min/tests
  lint:
    name: flake8
