---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-graalvm-debian-min
    image: debian:9

provisioner:
  name: ansible
  options:
    vvv: True
  playbooks:
    converge: ../graalvm-max-online/converge.yml

scenario:
  name: debian-min-graalvm-max-online

verifier:
  name: testinfra
  directory: ../graalvm-max/tests
