---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-graalvm-ubuntu-min
    image: ubuntu:18.04
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-min-online/converge.yml

scenario:
  name: ubuntu-min-graalvm-min-online

verifier:
  name: testinfra
  directory: ../graalvm-min/tests