---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-graalvm-fedora-two-times
    image: fedora:32
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: fedora-graalvm-two-times

verifier:
  name: testinfra
  directory: tests
  lint:
    name: flake8
