---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '17.0.7'

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
