---
provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-min-online/converge.yml

dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-graalvm-default
    image: ubuntu:22.04

verifier:
  name: testinfra
  directory: ../graalvm-min/tests
