---
provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-max-online/playbook.yml
  lint:
    name: ansible-lint

dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-graalvm-default
    image: ubuntu:18.04

scenario:
  name: default

verifier:
  name: testinfra
  directory: ../graalvm-max/tests
  lint:
    name: flake8
