---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: ansible-role-graalvm

  post_tasks:
    - name: Verify graalvm facts
      ansible.builtin.assert:
        that:
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.java_version is version('21.0.2', '==')
          - ansible_local.graalvm.general.home is defined
          - ansible_local.graalvm.general.home is match ('/opt/graalvm/jdk-21.0.2')

    - name: Install find - required for tests (dnf)
      ansible.builtin.dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
