---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-graalvm-ubuntu-max
    image: ubuntu:22.04

provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-max-offline/converge.yml

scenario:
  name: ubuntu-max-graalvm-max-offline

verifier:
  name: testinfra
  directory: ../graalvm-max/tests
