---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-graalvm-opensuse
    image: opensuse/leap:15.1

provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-max-online/converge.yml

scenario:
  name: opensuse-graalvm-max-online

verifier:
  name: testinfra
  directory: ../graalvm-max/tests
