---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-graalvm-opensuse
    image: opensuse/leap:15.1
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-max-online/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: opensuse-graalvm-max-online

verifier:
  name: testinfra
  directory: ../graalvm-max/tests
  lint:
    name: flake8
