---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8

platforms:
  - name: ansible-role-graalvm-debian-max
    image: debian:12
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../graalvm-min-offline/converge.yml

scenario:
  name: debian-max-graalvm-min-offline

verifier:
  name: testinfra
  directory: ../graalvm-min/tests
