---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create local archive directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ graalvm_local_archive_dir }}'
      delegate_to: localhost

    - name: download GraalVM for offline install
      get_url:
        url: "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.2/graalvm-ce-java8-linux-amd64-19.3.2.tar.gz"
        dest: '{{ graalvm_local_archive_dir }}/graalvm-19.3.2-java8.tar.gz'
        force: no
        timeout: '{{ graalvm_download_timeout_seconds }}'
        mode: 'u=rw,go=r'
      delegate_to: localhost


  roles:
    - role: ansible-role-graalvm
      graalvm_java_version: '8'
      graalvm_version: '19.3.2'
      graalvm_use_local_archive: true
      graalvm_redis_filename: 'graalvm-19.3.2-java8.tar.gz'
      graalvm_redis_sha256sum: '7598364ed9c4e5c0f936f37275172e84218984f25f51685ac2f501ac1a2d43bf'

  post_tasks:
    - name: verify graalvm facts
      assert:
        that:
          - ansible_local.graalvm.general.version is defined
          - ansible_local.graalvm.general.java_version is defined
          - ansible_local.graalvm.general.home is defined

    - name: install find - required for tests (dnf)
      dnf:
        name: findutils
        state: present
      when: ansible_pkg_mgr == 'dnf'
