---
name: molecule tests

on:
  push:
    branches:    
      - '**'        # matches every branch
  pull_request:
    branches:
      - 'master'

jobs:
  molecule:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scenarios:
          - default
          - centos-max-graalvm-max-offline
          - centos-max-graalvm-min-offline
          - centos-min-graalvm-max-online
          - centos-min-graalvm-min-online
          - debian-max-graalvm-max-offline
          - debian-max-graalvm-min-offline
          - debian-min-graalvm-max-online
          - debian-min-graalvm-min-online
          - fedora-graalvm-max-online
          - fedora-graalvm-two-times
          - opensuse-graalvm-max-online
          - ubuntu-max-graalvm-max-offline
          - ubuntu-max-graalvm-max-online
          - ubuntu-max-graalvm-min-offline
          - ubuntu-min-graalvm-min-online
          - ubuntu-min-graalvm-max-online
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Use Cache
        uses: actions/cache@v3.0.1
        with:
          path: ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Molecule install dependencies
        run: ./moleculew wrapper-install

      - name: Molecule display versions
        run: ./moleculew wrapper-versions

      - name: Molecule test
        run: "./moleculew test --scenario-name=${{ matrix.scenarios }}"
